cms/article/urls.py
from django.conf.urls import url, include
from article.views import index, article, peginate

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^peginate/(?P<page>\d+)$', peginate, name='peginate'),
    url(r'^article/(?P<slug>[\w_-]+)/$', article, name='article')
]

cms/cms/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('article.urls', namespace='article'))
]

# Manage media files in debug mode
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/article/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import gettext_lazy as _


class Article(models.Model):
    """Article model"""
    title = models.CharField(_('Article title'), max_length=250)
    slug = models.SlugField(_('Article slug'), max_length=250)
    image = models.ImageField(_('Article image'), upload_to='article', blank=True, null=True)
    content = models.TextField(_('Article content text'))
    is_published = models.BooleanField(_('Article is published'), default=False)

    def __unicode__(self):
        return self.title

cms/article/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_GET
from django.core.paginator import Paginator, EmptyPage

from article.models import Article


def peginate_articles(page):
    """peginate through articles"""
    articles = Article.objects\
        .filter(is_published=True)\
        .order_by('-id')

    paginator = Paginator(articles, settings.ARTICLES_PER_PAGE)
    try:
        articles = paginator.page(int(page))
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)

    return articles


@require_GET
def index(request):
    """View for main page"""
    articles = peginate_articles(1)

    return render(
        request,
        'article/index.html',
        {'articles': articles}
    )


@require_GET
def peginate(request, page):
    """peginate views"""
    articles = peginate_articles(page)
    return render(request, 'article/articles_list.html', {
        'articles': articles
    })


@require_GET
def article(request, slug):
    """Article view"""
    article = get_object_or_404(Article, slug=slug, is_published=True)
    return render(request, 'article/article.html', {
        'article': article
    })

cms/article/templates/article/article.html
{% extends "article/base.html" %}

{% load i18n %}

{% block title %}{% trans "Article - " %}{{ article.title}}{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li><a href="{% url 'article:index' %}">{% trans "Articles" %}</a></li>
        <li class="active">{{article.title}}</li>
    </ol>
{% endblock %}


{% block content %}
    <div class="article-title page-header">
        <h1>{{article.title}}</h1>
    </div>
    <div class="article-image text-center">
        <img src="{{article.image.url}}" alt="" />
    </div>
    <div class="article-content text-justify">
        <p>{{article.content|safe}} </p>
    </div>
{% endblock %}

cms/article/templates/article/articles_list.html
{% for article in articles %}
<tr {% if not articles.has_next %}data-last="true"{% endif %}>
    <td>
        <a href="{% url 'article:article' slug=article.slug %}">{{article.title}}</a>
    </td>
</tr>
{% endfor %}

cms/article/templates/article/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Main page{% endblock %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'article/css/base.css' %}" charset="utf-8">
    </head>
    <body>
        <div class="container">
            {% block breadcrumbs %}{% endblock %}
            {% block content  %}{% endblock %}
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
        <script src="{% static 'article/js/base.js' %}" charset="utf-8"></script>
    </body>
</html>

cms/article/templates/article/index.html
{% extends "article/base.html" %}

{% load i18n %}

{% block title %}{% trans "Articles" %}{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="active">{% trans "Articles" %}</li>
    </ol>
{% endblock %}

{% block content %}
    <table class="table table-hover">
        <tbody>
            {% include "article/articles_list.html"  with articles=articles %}
        </tbody>
    </table>
    <div class="">
        <a href="#" class="btn btn-primary load-more {% if not articles %}disabled{% endif%}">
            {% trans "Load more"%}
        </a>
    </div>
{% endblock %}